### ISSUE TITLE
downsampling error

### ISSUE THREAD

**Issue by mohayl** [elisejiuqizhang/USAD-on-WADI-and-SWaT#1]
when you downsample you removed 25 features, because the columns are objects due to ',' separator used in the data.

#Downsampling
normal=normal.groupby(np.arange(len(normal.index)) // 5).mean()
normal.shape

(99000, 26)

it should be  (99000, 51)

**Comment by elisejiuqizhang** [comment]
I'll look into it when I got back to the office! thanks for pointing it out

**Comment by elisejiuqizhang** [comment]
I think moving the block of "# Transform all columns into float64" in front of the downsampling block seemingly solved this problem! Just a sec till I rerun the notebook and update it

**Comment by mohayl** [comment]
yes it solved the problem
