### ISSUE TITLE
Paper Results

### ISSUE THREAD

**Issue by dadodimauro** [elisejiuqizhang/USAD-on-WADI-and-SWaT#3]
Hi, thanks for your work!
I am trying to implement the USAD algorithm in my master thesis, and I would like to ask you if you were able to obtain the same results of the paper, and if yes hou you did it.
Thanks again

**Comment by elisejiuqizhang** [comment]
I didn't really go too far to do feature engineering or tune the parameters according to the author's implementation so I'm really not sure if mine could really get there?😅

**Comment by dadodimauro** [comment]
Ok thanks a lot!
